---
title: "ANALISE DE BASE DE DADOS"
output:
  html_document:
    df_print: paged
  pdf_document: default
---

<strong>ANALISE DE BASE DE DADOS:</strong>
<br>

```{r Pacotes, include=FALSE}
  library(funModeling) 
  library(tidyverse) 
  library(Hmisc)
  library(GGally)

  ################################
  # INSIRA SUA BASE DE DADOS AQUI!
  
  MyData <- iris # <----- DADOS

  ################################
  
  
  MyData <- as.data.frame(MyData)
```

<br>
<strong>INFORMACOES SOBRE A BASE DE DADOS</strong> 
<br>

```{r glimpse, echo=FALSE}
   glimpse(MyData)
```

<br>
<strong>INFORMACOES SOBRE AS COLUNAS:</strong>
<br>

```{r df_status, echo=FALSE}
  df_status(MyData)
```

<br>
<strong>FREQUENCIA DOS DADOS CATEGORICOS:</strong>
<br>

```{r freq, echo=FALSE, fig.width=12, message=TRUE, warning=TRUE}
  freq(MyData)
```

<br>
<strong>DESCRICAO DOS DADOS NUMERICOS:</strong>
<br>

```{r profiling_num, echo=FALSE}
  profiling_num(MyData)
```

<br>
<strong>GRAFICO DOS DADOS NUMERICOS:</strong>
<br>

```{r plot_num, echo=FALSE, fig.width=12}
  plot_num(MyData)
```

<br>
<strong>DESCRICAO E ESTATISTICA GERAL DOS DADOS:</strong>
<br>

```{r describe}
  describe(MyData)
```

<br>
<strong>CORRELACAO DOS DADOS:</strong>
<br>

```{r ggcorr, echo=FALSE, fig.width=12, message=FALSE, warning=FALSE}
ggcorr(MyData, geom = "blank", label = TRUE, hjust = 0.75) +
  geom_point(size = 10, aes(color = coefficient > 0, alpha = abs(coefficient) > 0.5)) +
  scale_alpha_manual(values = c("TRUE" = 0.25, "FALSE" = 0)) +
  guides(color = FALSE, alpha = FALSE)
```

<br>
<strong>CORRELACAO COMPLETA DOS DADOS:</strong>
<br>

```{r ggpairs, fig.height=12, fig.width=12, message=FALSE, warning=FALSE}
  ggpairs(MyData,
          aes(color = Species))
```